development:
        validation: 'http://localhost:8888/validate'
        payment: 'http://localhost:9090/payment'

production:
        validation: 'http://localhost:8888/validate'
        payment: 'http://localhost:9090/payment'
